### ISSUE TITLE
Where's data.json?

### ISSUE THREAD

**Issue by n-kb** [paulloz/police-data-index#1]
Would be nice to be able to push requests to `data.json`, e.g. to fix typos, add a file...

**Comment by paulloz** [comment]
The `tsv` file containing the data will shortly be made available here (when the website actually launches). For now we're working with incomplete data for testing purposes.  
Otherwise, if you spot a typo outside of the datasets, feel free to tell us here.
🙂

**Comment by paulloz** [comment]
The data file is now available in the repo at [/public/data.tsv](https://github.com/paulloz/la-boite-noire/blob/master/public/data.tsv).
